# Generated by Django 6.0.6 on 2026-06-05 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('target_date', models.DateField(help_text='Data per cui è stata richiesta la previsione')),
                ('temperature', models.FloatField(help_text='Temperatura in gradi Celsius')),
                ('weather_condition', models.CharField(help_text='Es. Soleggiato, Pioggia, Nuvoloso', max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRequestTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'date'), name='unique_user_daily_request'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('ip_address', 'date'), name='unique_ip_daily_request')],
            },
        ),
    ]
